
import java.awt.Frame;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ALIBHAI
 */
public class forget extends javax.swing.JFrame {
 int imagesequence[]= new int[6];
        int imagetemp;int xo1,yo1,xo2,yo2,xo3,yo3,xo4,yo4,xo5,yo5;
    //int imagesequence[];
    int flag=0,i=0;
        int selectedimagecount=0;
        int xviewport,yviewport;
        int x,y;
        int p,q;
        Random random = new Random();
        int phase=0;
        int x1=0,y1=0,x2=0,y2=0,x3=0,y3=0,x4=0,y4=0,x5=0,y5=0;
        int selectedimage=0;InputStream music;
    AudioStream audios;
    String temp;
    
    /**
     * Creates new form forget
     */
    public forget() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        unametextfield = new javax.swing.JTextField();
        availableimagespanel = new javax.swing.JPanel();
        ImageIcon img1= new ImageIcon(((new ImageIcon("images\\01.jpg")).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
        image1 = new javax.swing.JButton(img1);
        ImageIcon img2= new ImageIcon(((new ImageIcon("images\\02.jpg")).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
        image2 = new javax.swing.JButton(img2);
        ImageIcon img3= new ImageIcon(((new ImageIcon("images\\03.jpg")).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
        image3 = new javax.swing.JButton(img3);
        ImageIcon img4= new ImageIcon(((new ImageIcon("images\\04.jpg")).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
        image4 = new javax.swing.JButton(img4);
        ImageIcon img5= new ImageIcon(((new ImageIcon("images\\05.jpg")).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
        image5 = new javax.swing.JButton(img5);
        ImageIcon img6= new ImageIcon(((new ImageIcon("images\\06.jpg")).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
        image6 = new javax.swing.JButton(img6);
        ImageIcon img7= new ImageIcon(((new ImageIcon("images\\07.jpg")).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
        image7 = new javax.swing.JButton(img7);
        ImageIcon img8= new ImageIcon(((new ImageIcon("images\\08.jpg")).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
        image8 = new javax.swing.JButton(img8);
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        selectbutton = new javax.swing.JButton();
        nbutton = new javax.swing.JButton();
        ImageIcon currentimg= new ImageIcon(((new ImageIcon("C:\\pccp\\src\\images\\noimage.jpg")).getImage()).getScaledInstance(450, 450, java.awt.Image.SCALE_SMOOTH));
        currentimage = new javax.swing.JButton(currentimg);
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        clickbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("    Username");

        unametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unametextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(unametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        availableimagespanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        image1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image1ActionPerformed(evt);
            }
        });

        image2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image2ActionPerformed(evt);
            }
        });

        image3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image3ActionPerformed(evt);
            }
        });

        image4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image4ActionPerformed(evt);
            }
        });

        image5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image5ActionPerformed(evt);
            }
        });

        image6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image6ActionPerformed(evt);
            }
        });

        image7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image7ActionPerformed(evt);
            }
        });

        image8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image8ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("  Image Box");

        javax.swing.GroupLayout availableimagespanelLayout = new javax.swing.GroupLayout(availableimagespanel);
        availableimagespanel.setLayout(availableimagespanelLayout);
        availableimagespanelLayout.setHorizontalGroup(
            availableimagespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, availableimagespanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(availableimagespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(availableimagespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(availableimagespanelLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(image3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(image5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(image7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(availableimagespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(availableimagespanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        availableimagespanelLayout.setVerticalGroup(
            availableimagespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableimagespanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(availableimagespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(availableimagespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(availableimagespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(availableimagespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        selectbutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        selectbutton.setText("Select");
        selectbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectbuttonActionPerformed(evt);
            }
        });

        nbutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        nbutton.setText("Next");
        nbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(selectbutton)
                .addGap(54, 54, 54)
                .addComponent(nbutton)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectbutton)
                    .addComponent(nbutton))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setAutoscrolls(true);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        clickbutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        clickbutton.setText("Click");
        clickbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbuttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("  Audio Box");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton5))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton15)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton9)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton10))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton11)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton12)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton13))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(clickbutton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton14)))
                        .addGap(14, 14, 14))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton2))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton15))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(clickbutton)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(availableimagespanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(currentimage, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(availableimagespanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(currentimage, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void image1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image1ActionPerformed
        // TODO add your handling code here:
       if(evt.getActionCommand().equals(""))
   {
       imagetemp=1;
    ImageIcon ic1=new ImageIcon(getClass().getResource("/images/01.jpg"));
  currentimage.setIcon(ic1); //new ImageIcon(getClass().getResource("/images/"+imagenames[i]));}
   } 
    }//GEN-LAST:event_image1ActionPerformed

    private void selectbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectbuttonActionPerformed
        // TODO add your handling code here:
      if(evt.getActionCommand().equals("select"))   
    {
       if(selectedimagecount<=5)
        {
            if(selectedimagecount==0)
            {
       // ImageIcon ic1= new ImageIcon(((new ImageIcon(getClass().getResource("/images/0"+imagetemp+".jpg"))).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
   //  selectedimage1.setIcon(ic1);  
     imagesequence[1]=imagetemp;
               selectedimagecount++; 
              // buttondisabler();
              return;
             }
            
            if(selectedimagecount==1)
            {//ImageIcon ic1=new ImageIcon(getClass().getResource("/images/01.jpg"));
     //   ImageIcon ic1= new ImageIcon(((new ImageIcon(getClass().getResource("/images/0"+imagetemp+".jpg"))).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
     //selectedimage2.setIcon(ic1);  
     imagesequence[2]=imagetemp;
               selectedimagecount++;
              // buttondisabler();
               return;
            }
            
            if(selectedimagecount==2)
            {
       // ImageIcon ic1= new ImageIcon(((new ImageIcon(getClass().getResource("/images/0"+imagetemp+".jpg"))).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
     //selectedimage3.setIcon(ic1);  
     imagesequence[3]=imagetemp;
               selectedimagecount++;
     //          buttondisabler();
               return;
            }
            
            if(selectedimagecount==3)
            {
       // ImageIcon ic1= new ImageIcon(((new ImageIcon(getClass().getResource("/images/0"+imagetemp+".jpg"))).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
     //selectedimage4.setIcon(ic1);  
     imagesequence[4]=imagetemp;
               selectedimagecount++;
       //        buttondisabler();
               return;
            }
            
            if(selectedimagecount==4)
            {
        //ImageIcon ic1= new ImageIcon(((new ImageIcon(getClass().getResource("/images/0"+imagetemp+".jpg"))).getImage()).getScaledInstance(75, 60, java.awt.Image.SCALE_SMOOTH));
     //selectedimage5.setIcon(ic1);  
     imagesequence[5]=imagetemp;
               selectedimagecount++;
               selectbutton.setVisible(false);
       //        buttondisabler();
               return;
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_selectbuttonActionPerformed
    }
    private void image2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image2ActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals(""))
   {
       imagetemp=2;
    ImageIcon ic1=new ImageIcon(getClass().getResource("/images/02.jpg"));
  currentimage.setIcon(ic1); 
   }     
    }//GEN-LAST:event_image2ActionPerformed

    private void image3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image3ActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals(""))
   {
       imagetemp=3;
    ImageIcon ic1=new ImageIcon(getClass().getResource("/images/03.jpg"));
  currentimage.setIcon(ic1); 
   }     
    }//GEN-LAST:event_image3ActionPerformed

    private void image4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image4ActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals(""))
   {
       imagetemp=4;
    ImageIcon ic1=new ImageIcon(getClass().getResource("/images/04.jpg"));
  currentimage.setIcon(ic1); 
   }     
    }//GEN-LAST:event_image4ActionPerformed

    private void image5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image5ActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals(""))
   {
       imagetemp=5;
    ImageIcon ic1=new ImageIcon(getClass().getResource("/images/05.jpg"));
  currentimage.setIcon(ic1); 
   }     
    }//GEN-LAST:event_image5ActionPerformed

    private void image6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image6ActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals(""))
   {
       imagetemp=6;
    ImageIcon ic1=new ImageIcon(getClass().getResource("/images/06.jpg"));
  currentimage.setIcon(ic1); 
   }     
    }//GEN-LAST:event_image6ActionPerformed

    private void image7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image7ActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals(""))
   {
       imagetemp=7;
    ImageIcon ic1=new ImageIcon(getClass().getResource("/images/07.jpg"));
  currentimage.setIcon(ic1); 
   }     
    }//GEN-LAST:event_image7ActionPerformed

    private void image8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image8ActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals(""))
   {
       imagetemp=8;
    ImageIcon ic1=new ImageIcon(getClass().getResource("/images/08.jpg"));
  currentimage.setIcon(ic1); 
   }     
    }//GEN-LAST:event_image8ActionPerformed

    private void nbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbuttonActionPerformed
        // TODO add your handling code here:
        int seqm=0;
     for(int i=1;i<=5;i++)
     {
         seqm=seqm*10+imagesequence[i];
     }
     System.out.println(seqm);
     String uname = unametextfield.getText();
     try
        {
        if(uname.equals(""))
        {
             JOptionPane.showMessageDialog(new Frame(),"Enter Username");
        }
        
        else
        {
            
            Class.forName("com.mysql.jdbc.Driver");
            String connectionQuery="jdbc:mysql://localhost:3306/pccp";  
            Connection con = DriverManager.getConnection(connectionQuery,"root",""); 
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select seq,audio from plog where uname='"+uname+"'"); 
            while(rs.next())
            {
               if((rs.getInt("seq")==seqm)||(rs.getString("audio")==temp))
               {
               // if((rs.getInt("seq")==seqm))
                   //System.out.println(seqm);
                    JOptionPane.showMessageDialog(new Frame(),"successfull");
                   // new NewJFrame3().setVisible(true);
                  //  this.setVisible(false);
                  sig nf1 = new sig();
                  nf1.unametextfield.setText(this.unametextfield.getText());
                  nf1.setVisible(true);
         this.setVisible(false);
               }
                else
                {
                    JOptionPane.showMessageDialog(new Frame(),"Login failed");
                    new NewJFrame3().setVisible(true);
                    this.setVisible(false);
                }
            }
        }
         /* 
        }
         if(flag==1)
        {
           
            //if((seqn==seqm)&&(aud==temp))
           // {
                JOptionPane.showMessageDialog(new Frame(),"successfully logined");
           // }
           
         
        if(flag!=1)
        {
            JOptionPane.showMessageDialog(new Frame(),"Login failed due to incorrect Username");
            //nextbutton.setEnabled(true);
            
        }
        */
         }//try closed
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(new Frame()," Error :"+e); 
        }


    }//GEN-LAST:event_nbuttonActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
               try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a4.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton4.setActionCommand("4");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
               try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a6.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton6.setActionCommand("6");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void clickbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickbuttonActionPerformed
        // TODO add your handling code here:
        AudioPlayer.player.stop(audios);
      temp=buttonGroup1.getSelection().getActionCommand(); 
      System.out.println(temp);
      clickbutton.setVisible(false);
    }//GEN-LAST:event_clickbuttonActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
               try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a7.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton7.setActionCommand("7");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
         try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a1.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton1.setActionCommand("1");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}           
  
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
               try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a2.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton2.setActionCommand("2");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
               try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a14.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton14.setActionCommand("14");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
               try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a5.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton5.setActionCommand("5");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
               try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a15.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton15.setActionCommand("15");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
               try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a11.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton11.setActionCommand("11");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
               try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a12.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton12.setActionCommand("12");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
               try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a13.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton13.setActionCommand("13");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
               try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a3.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton3.setActionCommand("3");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
          try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a9.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton9.setActionCommand("9");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
          try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a8.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton8.setActionCommand("8");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
        
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
          try{
 AudioPlayer.player.stop(audios);
music=new FileInputStream(new File("src\\sound\\a10.wav"));
audios = new AudioStream(music);
AudioPlayer.player.start(audios);
 jRadioButton10.setActionCommand("10");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}       
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void unametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unametextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel availableimagespanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clickbutton;
    private javax.swing.JButton currentimage;
    private javax.swing.JButton image1;
    private javax.swing.JButton image2;
    private javax.swing.JButton image3;
    private javax.swing.JButton image4;
    private javax.swing.JButton image5;
    private javax.swing.JButton image6;
    private javax.swing.JButton image7;
    private javax.swing.JButton image8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JButton nbutton;
    private javax.swing.JButton selectbutton;
    public javax.swing.JTextField unametextfield;
    // End of variables declaration//GEN-END:variables
}
